version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - fusion-net

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/data:/app/app/data
    networks:
      - fusion-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - fusion-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - fusion-net
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - fusion-net
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

networks:
  fusion-net:
    driver: bridge

