name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t skywalkerdarth/backend:latest ./backend

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Push Docker image
      - name: Push Docker image
        run: docker push skywalkerdarth/backend:latest

      # Step 6: Setup SSH for deployment
      - name: Setup SSH for Deployment
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 7: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.111.198.239 "
            docker pull skywalkerdarth/backend:latest &&
            docker-compose -f ~/fusionpact-devops-challenge/docker-compose.yml down &&
            docker-compose -f ~/fusionpact-devops-challenge/docker-compose.yml up -d
          "

